import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
  const [description, setDescription] = useState("");
  return (
    <div className=" flex justify-between flex-col h-screen ">
      <Head>
        <title>AI App Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-10 max-w-5xl flex flex-col w-full gap-3">
        <h1 className="text-center text-4xl mb-10">AI App Ideas</h1>

        <div className="flex justify-center">
          <div className="w-3/4 flex flex-col items-center gap-5">
            <div className="w-3/5">
              <div className="text-center">Give the ai some hints...</div>
              <textarea
                rows={2}
                name="description"
                id="description"
                className="shadow-sm  border block w-full resize-none border-t py-2 placeholder-gray-500 sm:text-sm p-5 focus:outline-none"
                placeholder="ex: image generation, legal, etc.."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>
            <button className="border text-xl py-2 px-5 rounded-md bg-white hover:bg-slate-200 shadow-md ">
              Generate
            </button>
            <div className="w-full flex flex-col gap-1">
              <div>Results...</div>
              <div className="border w-full py-2 px-5">
                <div>
                  <div className="text-xl">Instagram for SD</div>
                  <div className="pl-5">Hello</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <footer className="border-t-2 text-center pt-2 mt-40">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by Calum and Justin
          </a>
        </footer>
      </div>
    </div>
  );
}
